### ISSUE TITLE
[Dapp] Farming Index page - Front design

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#1]
**Description**
---

New implementation, in React and Remix, of Farming page in Carbonable Launchpad.

**Design reference**
https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?node-id=0%3A1&t=a2NYxoXVVLR9uNCd-1

**Prerequis**
---
The Carbonable/carbonable-dapp#2 need to be finish for this Issue.

**Acceptance Criteria**
---
- [ ] Validated in multi Browser (Chrome, Firefox, Brave)
- [ ] Validated on Smartphone (iPhone, Android)
- [ ] Be connected with Starknet wallet
