### ISSUE TITLE
Add dApp features from home repo

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-dapp#10]
**Acceptance Criteria**
---
- [x] Allow user to connect with wallet
- [x] Allow user to get starknet id if exists
- [ ] Test at: https://dev-carbonable-dapp.fly.dev/
