### ISSUE TITLE
[Infra] Migrate Database to Postgres Cluster in Fly.io

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#111]
**Description**
---
Migrate all single Postgres database to Postgres Cluster in Fly.io

List for testing of database to migrate : 
- [x] dev-carbonable-db
- [x] dev-carbonable-indexer-db

**Suggested Evolution**
---
Migrate all single Postgres database to Postgres Cluster in Fly.io

**Acceptance Criteria**
---
List in production of database to migrate are :
- [x] preprod-bridge-backend-db
- [x] preprod-carbonable-db
- [x] preprod-carbonable-indexer-db
- [x] prod-bridge-backend-db
- [x] prod-carbonable-db
- [x] prod-carbonable-indexer-db
