### ISSUE TITLE
[Infra] Save and persistent storage for Dapp logs

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#112]
**Description**
---
Save and persistent storage for Dapp logs

List for testing of database to migrate : 
- [ ] dev-carbonable-dapp
- [ ] dev-carbonable-home

**Suggested Evolution**
---
To determine : which app using to persiste logs from Dapp on Fly.io

**Acceptance Criteria**
---
List in production of database to migrate are :
- [ ] preprod-carbonable-home
- [ ] preprod-carbonable-indexer

- [ ] prod-bridge-backend
- [ ] prod-bridge-frontend
- [ ] prod-carbonable-dapp
- [ ] prod-carbonable-home
- [ ] prod-carbonable-indexer
