### ISSUE TITLE
Design UX & UI - Farming Project Page

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-dapp#13]
**Description**
---
The Farming Project page of a given farming pool

figma her: https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?node-id=48%3A2365&t=Wpf34AORSqH2rldm-0

Important: 
* All use-cases taken into consideration: 
- Connected vs not connected
- Yield only, vs Offset only, versus both

**Acceptance Criteria**
---
- [ ] The design of the UX on Figma
- [ ] The design of the UI on Figma
- [ ] The design elements are exportable
