### ISSUE TITLE
Design UX & UI - Farming Index page

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#2]
**Description**
---
Design the UX and the UI for the Farming page on the launchpad.

Inspirations: 
* Osmosis: https://app.osmosis.zone/pools
* Beefi: https://app.beefy-finance.cn.com/

Specs: Excalidraw: https://app.excalidraw.com/s/4BTLOTSvKjp/sLJ9vi7gRo

Some guidance, in the context of carbonable: 
* 1 "pool" = 1 project
* search "card" or "line" should include information applicable to the project as a whole (and not the individual connected)
* should reflect the carbonable brand identity
* should be able to apply relevant filters (at a bare minimum: All - My Projects and why not Yield - Offset): those fitlers will be very important especially in the future when the list will be long. 

**Acceptance Criteria**
---
- [x] The design of the UX on Figma
- [x] The design of the UI on Figma
- [x] The design elements are exportable
