### ISSUE TITLE
[Dapp] Farming Project Page

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#20]
**Description**
---

Implementation ofInner Farming Page in Carbonable Dapp. 

**Prerequis**
---
The #13  need to be finish for this Issue.

**Acceptance Criteria**
---
- [ ] Validated in multi Browser (Chrome, Firefox, Brave)
- [ ] Validated on Smartphone (iPhone, Android)
- [ ] Be connected with Starknet wallet
