### ISSUE TITLE
Portfolio page - Quickwin 

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#26]
**Description**
---
Implementation of Portfolio page in Carbonable Dapp:
https://carbonable.io/portfolio

Need to find on the page:
- Integration or link to [Mint Square](https://mintsquare.io/starknet) of the portfolio of the user

**Acceptance Criteria**
---
- [ ] Validated in multi Browser (Chrome, Firefox, Brave)
- [ ] Validated on Smartphone (iPhone, Android)
- [ ] Link of Mint Square are able to display Carbonable NFTs
