### ISSUE TITLE
Design UX & UI - Projects page

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#3]
**Description**
---
Design the UX and the UI for the Funding page on the launchpad.

**Acceptance Criteria**
---
- [x] The design of the UX on Figma
- [x] The design of the UI on Figma
- [x] The design elements are exportable
