### ISSUE TITLE
Multi network ABI management

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-dapp#37]
**Description**
---
Use env variable to load the correct ABI.

**Acceptance Criteria**
---

- [ ] Env variable network is set with either: TESTNET, TESTNET2 or MAINET
- [ ] Remove code in Header.tsx to force TESTNET2 on every environment
- [ ] Manage default display if data are not available on the selected network

**Additional context**
---
None
