### ISSUE TITLE
Design UX & UI - Portfolio

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#4]
**Description**
---
Design the UX and the UI for the portfolio page on the launchpad. 

- We need to decided if we show on this new design page, the number of NFT you have per project. 

Old portfolio
![Old-portfolio](https://user-images.githubusercontent.com/3840436/200205155-2d869a20-0ef1-4502-8d0b-23a97c24495a.png)

**Acceptance Criteria**
---

- [ ] The design of the UX on Figma
- [ ] The design of the UI on Figma
- [ ] The design elements are exportable
