### ISSUE TITLE
target Portfolio page

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#5]
**Description**
---
New implementation, in React, of Portfolio page in Carbonable Launchpad:
https://carbonable.io/portfolio

Need to find on the page:
- Wallet Address (Braavos and Argent X)
- Menu with links to the left 

**Prerequis**
---
The Carbonable/carbonable-dapp#4 need to be finish for this Issue.

**Acceptance Criteria**
---
- [ ] Validated in multi Browser (Chrome, Firefox, Brave)
- [ ] Validated on Smartphone (iPhone, Android)
- [ ] Be connected with Starknet wallet
