### ISSUE TITLE
[Dapp] Project Preview page - CMS

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#6]
**Description**
---

New implementation, in React, of Projects preview in Carbonable Launchpad. 
From [Figma Project Preview pages](https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?node-id=144%3A7290&t=Wpf34AORSqH2rldm-0)

Need to find on the page:
- Project overview
- Project holders
- Impact

**Acceptance Criteria**
---
- [ ] Validated in multi Browser (Chrome, Firefox, Brave)
- [ ] Validated on Smartphone (iPhone, Android)
- [ ] Be integrated with Sanity
