### ISSUE TITLE
Implement Apibara Indexer to listen starknet events and store data which come from on-chain

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#61]
**Description**
---
Implement Apibara Indexer to listen starknet events and store data which come from on-chain in a backend.

Scope: Projects+Minter / Launchpad

**Acceptance Criteria**
---

Features needed to be implement : 
- [ ] Integration and configuration of Indexer SDK
- [ ] Storage into database 
- [ ] Exposing APIs to access data

**Additional context**
---

Apibara - what does it offer?

An SDK (in Python and TypeScrypt) that allows you to listen to the events of the Starknet blockchain and store them in the database. You have to configure the SDK with the address of the smart contract and the name of the events (function) it has to listen to. 
Once configured and the backend that integrates the SDK launched/started, the events are "streamed" through the gRPC protocol and the backend needs to manage them as it wants  (processing, storage, etc...). 

This Indexer SDK must be integrated into a backend developed by the business/enterprise/architecture that wishes to use it. It is also necessary to configure the storage of these events (Prisma + Postrgesql for example) and to implement the APIs which must be exposed by this backend. 

Roadmap :
- Currently only two client SDKs:
	- **Python**: the most used and most battletested but it will not be maintained by Apibara in the futur (only community).
	- **TypeScrypt**: the most recent and least battletested, but it is this one that Apibara will maintain and improve. 
- New release during the week of december 19th to 23rd (either SDK TypeScrypt or both, I didn't ask the question). -> It is recommended to wait for this new release before implementing our Indexer. 
- In 2 to 4 months (or even 6 months), a serverless service, in the form of a lambda, will be proposed to consume the starknet events without having to host a backend/server. 

Library Indexer SDK : 
https://github.com/apibara/typescript-sdk

Proof of Concept :
It is recommended, if we want to make the implementation in TypeScrypt, to use the workshop made in this repo and replace the database connector by Prisma :
- Workshop : https://github.com/apibara/encode-club-workshop-nov22/tree/04-api-server

(For the moment, there is only a template in Python but not yet in TypeScrypt).

Starknet.ID Indexer :
https://github.com/starknet-id/indexer
