### ISSUE TITLE
[Dapp] Project preview - Mint section

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-dapp#63]
**Description**
---

New design from https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?node-id=233%3A7612&t=kY15vCBIjoQSbOTJ-0

Need to find on the page:
- Coming soon
- Mint 
- Soldout

**Acceptance Criteria**
---
- [ ] Validated in multi Browser (Chrome, Firefox, Brave)
- [ ] Validated on Smartphone (iPhone, Android)
- [ ] Be integrated with Testnet

**Comment by schwepps** [comment]
Blocked until design for soldout, waiting list, coming soon, etc. is finalized
