### ISSUE TITLE
[Dapp] Homepage After connection / Funding Projects page

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#7]
**Description**
---

New implementation, in React with Remix, of the Homepage of Carbonable Launchpad after connection with Starknet Wallet:
https://carbonable.io/launchpad

From [Figma pages](https://www.figma.com/file/23Xxeg0nagkmBodO0dlFfs/Carbonable---Design?node-id=0%3A1&t=pXmLBfOIFEZNlsHj-0)

Need to find on the Homepage:
![Image](https://user-images.githubusercontent.com/3840436/200203282-4311cfda-7bee-4e8a-980a-0222d9ad2ed3.PNG)

- Wallet Address (Braavos and Argent X)
- Menu with links to the left 

**Acceptance Criteria**
---
- [ ] Validated in multi Browser (Chrome, Firefox, Brave)
- [ ] Validated on Smartphone (iPhone, Android)
- [ ] Be able to connect Starknet Braavos wallet (https://braavos.app/)
- [ ] Be able to connect Starknet Argent X wallet (https://www.argent.xyz/argent-x/)
