### ISSUE TITLE
[Dapp] Homepage Before connection

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-dapp#8]
**Description**
---

New implementation, in React, of the Homepage of Carbonable Dapp:
https://carbonable.io/launchpad

From [Figma pages](https://www.figma.com/file/23Xxeg0nagkmBodO0dlFfs/Carbonable---Design?node-id=0%3A1&t=pXmLBfOIFEZNlsHj-0)

Need to find on the Homepage:
- Wallet bottom functional (Braavos and Argent X)
- Menu with links to the left 
![Menu Page](https://user-images.githubusercontent.com/3840436/200203464-d2ff9088-bd5a-40bf-a5ff-1885ba5cd36c.PNG)

- Central image MUST NOT BE BLUR with projects
![CEntral Page](https://user-images.githubusercontent.com/3840436/200203513-c311610c-4532-4fe7-a327-d8d1e53e9526.PNG)

**Acceptance Criteria**
---
- [x] Validated in multi Browser (Chrome, Firefox, Brave)
- [x] Validated on Smartphone (iPhone, Android)
- [x] Be able to connect Starknet Braavos wallet (https://braavos.app/)
- [x] Be able to connect Starknet Argent X wallet (https://www.argent.xyz/argent-x/)
