### ISSUE TITLE
Project State Management - Status

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-dapp#9]
**Description**
---
Projects have 3 statuses: 
- Active
- Sold out
- Coming soon

The information on the project page for each of those statuses changes 
See details here: https://www.figma.com/file/23Xxeg0nagkmBodO0dlFfs/Carbonable---Design?node-id=0%3A1&t=jWpSDoPMPWe1vo7S-1

Use connectionr has 3 statuses: 
- Connected => user can perform all actions
- Not connected => user can see everything but: cannot buy, cannot access menu elements (apart from the generic dashboard)

When a non-connected user tries to perform such actions, a pop up should appear telling him that he should connect his/her wallet. 

**Acceptance Criteria**
---

- [x] Desktop and mobile
- [x] All combination of project & user statuses tested
- [x] Auto connect wallet if not connected
- [x] Display transaction error
- [x] Display transaction success
- [x] Update supply left
- [x] Work with Braavos
- [x] Display loading action

**Additional context**
---
