### ISSUE TITLE
Display list of ongoing transactions

### ISSUE THREAD

**Issue by schwepps** [Carbonable/carbonable-dapp#92]
**Description**
---
Display the list of ongoing transactions to the user with a link to mintscan

**Acceptance Criteria**
---

- [ ] Display all transactions having a status prior to Accepted on L2
- [ ] Have a link to mintscan
- [ ] Transactions are displayed even if the user refreshes the page
- [ ] Each status has its color code
- [ ] The type of action is displayed (mint, yield, offset, etc.)

**Additional context**
---
None
